trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 
    jobs:
      - job:
        displayName: publish artifact to pipeline workspace and validate the terraform manifest
        steps:
          -  task: PublishPipelineArtifact@1
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform-aks'
              artifact: 'terraformaks'
              publishLocation: 'pipeline'
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-svc'
              backendAzureRmSubscriptionId: '01a0d38e-38ad-442e-be3f-ad1e760bd4f5'
              backendAzureRmResourceGroupName: 'terraform-tfstate-storage'
              backendAzureRmStorageAccountName: 'tfstatestoragebatch5'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-aks'
              allowTelemetryCollection: false