trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate_terraform
    jobs:
      - job:
        displayName: publish artifact to pipeline workspace and validate the terraform manifest
        steps:
          -  task: PublishPipelineArtifact@1
             displayName: Publish artifact
             inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraformtest/aks_provision'
              artifact: 'terraformaks'
              publishLocation: 'pipeline'
          - task: TerraformInstaller@0
            displayName: Install terraform
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: Terraform Init
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraformtest/aks_provision'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-svc'
              backendAzureRmSubscriptionId: '01a0d38e-38ad-442e-be3f-ad1e760bd4f5'
              backendAzureRmResourceGroupName: 'terraform-tfstate-storage'
              backendAzureRmStorageAccountName: 'tfstatestoragebatch5'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false
  - stage: plan_terraform
    displayName: terraform plan
    dependsOn:
       - "validate_terraform"
    jobs:
      - job: "terraformjobs"
        displayName: "Terraform > Install Init Plan"
        steps:
          - task: TerraformInstaller@0
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@0
            displayName: Terraform Init
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraformtest/aks_provision'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-aks-svc'
              backendAzureRmSubscriptionId: '01a0d38e-38ad-442e-be3f-ad1e760bd4f5'
              backendAzureRmResourceGroupName: 'terraform-tfstate-storage'
              backendAzureRmStorageAccountName: 'tfstatestoragebatch5'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false
          - task: TerraformCLI@0
            displayName: Terraform Plan
            inputs:
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraformtest/aks_provision'
              environmentServiceName: 'terraform-aks-svc'
              providerAzureRmSubscriptionId: '01a0d38e-38ad-442e-be3f-ad1e760bd4f5'
              commandOptions: '-out=$(System.DefaultWorkingDirectory)/terraform.tfplan'
              allowTelemetryCollection: false
              publishPlanResults: 'terraform.tfplan'
          - task: TerraformCLI@0
            displayName: Terraform show
            inputs:
              command: 'show'
              allowTelemetryCollection: false
              inputTargetPlanOrStateFilePath: '$(System.DefaultWorkingDirectory)/terraform.tfplan'
