apiVersion : apps/v1
kind: Deployment
metadata:
  name: appnginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appnginx
  template:
    metadata:
      labels:
        app: appnginx 
    spec:
      containers:
        - name: appnginx 
          image: aksregistryncj0l.azurecr.io/appnginx
          ports:
          - containerPort: 80