apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: aksregistryzjv3l.azurecr.io/customnginximage:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080