apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: aksregistryzjv3l.azurecr.io/customnginximage:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80